# Site settings
title: "CPhyGS: Cell Biology and Physiology Graduate Society cphygs.github.io"
email: cphygs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CPhyGS is the Cell Biology and Physiology Graduate Society!
  Representing graduate students in both the Cellular and
  Physiological Sciences department, and in the Cell and
  Developmental Biology graduate program, here at the 
  beautiful University of British Columbia
  Come join us today!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cphygs.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: cphygs

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Life Science Institute 
    link: lsi.ubc.ca
  option2:
    name: CPS
    link: cps.med.ubc.ca
  option3:
    name: CELL
    link: cell.med.ubc.ca
  option4:
    name: G+PS
    link: www.grad.ubc.ca

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown

# Show future posts
future: true

# Turn off date permalinks
permalink: none
